server:
  port: 10101
spring:
  application:
    name: gateway-default
    cloud:
        gateway:
          routes:
          - id: tms-default
            uri: lb://tms-default
            predicates:
            - Path=/tms/**
            filters:
            - StripPrefix=1
          - id: hub-default
            uri: lb://hub-default
            predicates:
            - Path=/hub/**
            filters:
            - StripPrefix=1
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defualtZone: http://localhost/8761/eureka