server:
  port: 10101
spring:
  application:
    name: gateway
    cloud:
        gateway:
          routes:
          - id: tms
            uri: lb://tms
            predicates:
            - Path=/tms/**
            filters:
            - StripPrefix=1
          - id: hub
            uri: lb://hub
            predicates:
            - Path=/hub/**
            filters:
            - StripPrefix=1
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defualtZone: http://localhost/8761/eureka