server:
  port: 8081
spring:
  application:
    name: hub-dev
  datasource:
    url: jdbc:mysql://localhost:3306/hub?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin123
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
